//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations.Schema;

namespace CompanyHRManagement
{
    using System;
    using System.Collections.Generic;

    public partial class Attendance
    {
        public int AttendanceID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public Nullable<System.TimeSpan> CheckIn { get; set; }
        public Nullable<System.TimeSpan> CheckOut { get; set; }
        public Nullable<int> OvertimeHours { get; set; }
        public string AbsenceStatus { get; set; }

        [NotMapped]
        public string MonthYear { get; set; }

        [NotMapped]
        public int WorkDays { get; set; }

        public virtual Employee Employee { get; set; }
    }
}
