//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyHRManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leaf
    {
        public int leaveID { get; set; }
        public Nullable<int> employeeID { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string reason { get; set; }
        public string status { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
