//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyHRManagement
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Message
    {
        public int MessageID { get; set; }
        public int SenderID { get; set; }
        public int ReceiverID { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> SentAt { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        //// Thêm thuộc tính này để hiển thị tên người gửi
        //public string SenderName { get; set; }
        //// dùng cho tin nhắn đã gửi
        //public string ReceiverName { get; set; }

        //[ForeignKey("SenderId")]
        //public virtual Employee SenderName { get; set; }

        //[ForeignKey("ReceiverId")]
        //public virtual Employee ReceiverName { get; set; }

    }
}
