//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations.Schema;
namespace CompanyHRManagement
{
    using System;
    using System.Collections.Generic;

    public partial class Salary
    {
        public int SalaryID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<decimal> BaseSalary { get; set; }
        public Nullable<decimal> Allowance { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<decimal> Penalty { get; set; }
        public Nullable<int> OvertimeHours { get; set; }
        public Nullable<int> SalaryMonth { get; set; }
        public Nullable<int> SalaryYear { get; set; }

        public virtual Employee Employee { get; set; }


        // =========== 2 property [NotMapped] để Show trong DataGridView ===========
        [NotMapped]
        public string FullName { get; set; }

        [NotMapped]
        public decimal TotalSalary { get; set; }
    }
}
