//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyHRManagement
{
    using System;
    using System.Collections.Generic;

    public partial class Salary
    {
        public int SalaryID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<decimal> BaseSalary { get; set; }
        public Nullable<decimal> Allowance { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<decimal> Penalty { get; set; }
        public Nullable<int> OvertimeHours { get; set; }
        public Nullable<int> SalaryMonth { get; set; }
        public Nullable<int> SalaryYear { get; set; }
        public virtual Employee Employee { get; set; }
        public string FullName { get; set; }

        public decimal TotalSalary
        {
            get
            {
                //?? 0: Nếu giá trị là null, lấy giá trị mặc định là 0.
                //(OvertimeHours ?? 0) * 50000: đảm bảo int? không bị lỗi khi nhân.
                return
                    (BaseSalary ?? 0) +
                    (Allowance ?? 0) +
                    (Bonus ?? 0) -
                    (Penalty ?? 0) +
                    ((OvertimeHours ?? 0) * 50000);
            }
        }

    }
}
